/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sevenzip;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CRCTest {
    @Test void notNull() {
        CRC classUnderTest = new CRC();
        assertNotNull(classUnderTest);
    }
}
